name: Upload Lambda Code to S3

on:
  push:
    paths:
    - 'backend/**' # Trigger only when files in the 'backend' directory are modified
  pull_request:
    paths:
    - 'backend/**'
jobs:
  upload-lambda:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Zip Lambda Code
      run: |
        cd backend
        zip -r lambda.zip index.js

    - name: Upload to S3
      run: |
        aws s3 cp backend/lambda.zip s3://2024-unlp-plotter-backend/lambda.zip
