name: Lambda CI/CD Pipeline

on:
  push:
    branches:
    - main # o tu rama principal
    paths:
    - 'lambda_function.py'
    - 'Dockerfile'
    - 'requirements.txt'
  pull_request:
    branches:
    - main
    paths:
    - 'lambda_function.py'
    - 'Dockerfile'
    - 'requirements.txt'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set Docker image tag based on commit SHA
      id: get-sha
      run: echo "sha_tag=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public # Usa 'public' si es un repositorio público en ECR
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1 # Cambia a tu región de AWS

    - name: Build Docker image
      run: |
        docker build -t my-lambda-image:${{ env.sha_tag }} .
        docker tag my-lambda-image:${{ env.sha_tag }} <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/my-lambda-repo:${{ env.sha_tag }}

    - name: Push Docker image to Amazon ECR
      run: |
        docker push <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/my-lambda-repo:${{ env.sha_tag }}

    - name: Update Lambda with new image
      run: |
        aws lambda update-function-code --function-name MyLambdaFunctionName --image-uri <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/my-lambda-repo:${{ env.sha_tag }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
