name: RTOS CI/CD

on:
  push:
    branches:
    - main
    paths:
    - 'rtos/**' # Solo ejecuta si se modifica algo dentro de rtos/
  pull_request:
    branches:
    - main
    paths:
    - 'rtos/**' # Solo ejecuta si el PR afecta archivos dentro de rtos/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up ESP32 Toolchain
      run: |
        docker pull espressif/idf:latest
        docker run --rm -v ${{ github.workspace }}:/project espressif/idf:latest /bin/bash -c "cd /project/rtos && idf.py build"

    - name: Build Docker image (optional, if needed)
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/plotter-rtos:latest ./rtos

    - name: Push Docker image to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/plotter-rtos:latest
