name: RTOS Release CI/CD

on:
  push:
    branches:
    - 'release/v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract version from branch name
      id: extract-version
      run: |
        VERSION=$(echo "${GITHUB_REF##*/}" | sed 's/^v//')
        echo "::set-output name=version::${VERSION}"

    - name: Set up ESP32 Toolchain
      run: |
        docker pull espressif/idf:latest
        docker run --rm -v ${{ github.workspace }}:/project espressif/idf:latest /bin/bash -c "cd /project/rtos && idf.py build"

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: rtos-build-${{ steps.extract-version.outputs.version }}
        path: rtos/build/
