name: RTOS CI/CD

on:
  push:
    branches:
    - main
    paths:
    - 'rtos/**'
  pull_request:
    branches:
    - main
    paths:
    - 'rtos/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Docker image tag based on commit SHA
      id: get-sha
      run: echo "::set-output name=sha_tag::$(git rev-parse --short HEAD)"

    - name: Set up ESP32 Toolchain
      run: |
        docker pull espressif/idf:latest
        docker run --rm -v ${{ github.workspace }}:/project espressif/idf:latest /bin/bash -c "cd /project/rtos && idf.py build"

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: rtos-build-${{ steps.get-sha.outputs.sha_tag }}
        path: rtos/build/
